### ISSUE TITLE
Create a cljsjs package for tv4 JSON schema validation library

### ISSUE THREAD

**Issue by okal** [okal/cljsjs-packages#1]
tv4 - https://github.com/geraintluff/tv4/
CLJSJS Packaging Guide - https://github.com/cljsjs/packages/wiki/Creating-Packages
## Tasks
- [x] Create directory structure.
- [x] Create externs.
- [x] Add README
- [x] Add build.boot
- [x] Add `package` task.
- [x] Install package locally. Test with advanced optimizations enabled.
